### ISSUE TITLE
Enhancement: Overlay tree on target

### ISSUE THREAD

**Issue by vermiculus** [abo-abo/avy#16] opened 2015-05-08 18:40 UTC
Instead of prefixing the tree to the target point, it would be nice if the tree could be overlaid on its target as to not disrupt positioning. Your eyes is looking in one spot for the target point; if there are multiple matches on the same (longer) line, the target point can visually move.

The only question to think about would be
> What should happen if two overlays would intersect?

The thing that makes Avy great, in my opinion, is the ability to see the whole path of the tree from the get-go (so you can position your hands -- unconsciously, of course). If two overlays were to intersect with each other (think `avy-goto-char` with an input of `SPC`), then that advantage would be lost. A possible solution is to customize the value per function (as an alist).

**Comment by abo-abo** [comment] 2015-05-08 18:53
I don't get it. The tree can be several chars wide, while the target can be only one char wide.

**Comment by vermiculus** [comment] 2015-05-08 19:00
Yeah, I know. Example, searching for `s`:

```
blah blah blah this is a word that starts with s
```

Instead of this:

```
blah blah blah thia*s is*s a word that d*startf*s with g*s
```
the ability to do this
```
blah blah blah thia* is* a word that d*tartf* with g*
```

The `*`s aren't really there -- it's just a way for me to denote where the overlay is.

**Comment by abo-abo** [comment] 2015-05-08 19:02
Just set `avy-goto-char-style` and `avy-goto-word-style` to `'at`. Done.

**Comment by tsdh** [comment] 2015-05-08 20:15
Duplicate of #5.

**Comment by vermiculus** [comment] 2015-05-09 01:37
My apologies :) :+1:

**Closed** 2015-05-09 01:37 UTC
