### ISSUE TITLE
avy-goto-line misbihaves when fci-mode is active

### ISSUE THREAD

**Issue by MadAnd** [abo-abo/avy#162] opened 2016-07-03 12:14 UTC
If `avy-goto-line` is invoked in buffer with active `fci-mode` [minor mode](https://github.com/alpaker/Fill-Column-Indicator), then on empty lines overlay keys are displayed after the fill column indicator.

![screenshot_20160703_150257](https://cloud.githubusercontent.com/assets/2280844/16545333/ae78d144-4130-11e6-8494-bf149e56f195.png)

**Comment by abo-abo** [comment] 2016-07-03 12:17
This is a duplicate of https://github.com/abo-abo/avy/issues/135. The decision was that the problem should be solved in `fci-mode` and not in `avy`.

**Closed by abo-abo** 2016-07-03 12:17 UTC

**Comment by MadAnd** [comment] 2016-07-03 12:19
Ah, sorry then. Should have checked closed isuues, not only open ones.
