### ISSUE TITLE
avy-goto-char unbinds key chord

### ISSUE THREAD

**Issue by joekain** [abo-abo/avy#288] opened 2019-10-27 16:45 UTC
I'm using avy version 20191024.2310 from melpa.  

I have a key chord bound to "jj" which invokes `counsel-M-x` like this:

`(key-chord-define-global "jj" 'counsel-M-x)`

If I use avy-goto-char and if I end up using "jj" to jump to a character the jump works but my key chord becomes unbound.

**Comment by abo-abo** [comment] 2019-10-30 12:32
I can reproduce. But this seems to be a `key-chord` issue. Avy does nothing else than call `read-key`.

This code is enough to break `key-chord`:

```elisp
(dotimes (i 2)
  (read-key "test: "))
```

Closing the issue as not relevant to `avy`.

In my opinion, you should not use `key-chord`, as Emacs was not designed around it. The package `key-chord` is very old and likely hacky. You can <kbd>M-x</kbd> `report-emacs-bug` if you would like a feature similar to key chord in core Emacs.

**Closed by abo-abo** 2019-10-30 12:32 UTC
