### ISSUE TITLE
Incorrect character highlighting in de-bruijn

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/avy#52] opened 2015-05-29 15:01 UTC
There seems to be a slight bug where the overlays start incorrectly marking decision chars when using the `de-bruijn` style.

**Example Jump text**
```emacs
;; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.

;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;
```

![avy-striping](https://cloud.githubusercontent.com/assets/5009546/7871155/f2a48d2a-0542-11e5-9861-4adf887a98d5.PNG)

It's also interesting to note that this bug is sporadic. Sometimes, it'll highlight it all correctly, and sometimes, it'll highlight it all wrong. This is an example where part of the highlighting is wrong.

**Comment by abo-abo** [comment] 2015-06-03 15:57
> Sometimes, it'll highlight it all correctly, and sometimes, it'll highlight it all wrong. This is an example where part of the highlighting is wrong.

Closing as not reproducible. If you manage to reliably reproduce it, please reopen.

**Comment by PythonNut** [comment] 2015-06-03 16:13
@tsdh You've reproduced this, right?

**Comment by tsdh** [comment] 2015-06-03 22:13
@PythonNut @abo-abo Yes, I can with the current avy version and emacs -Q.  See the two screenshots which also contain the recipe.

![screenshot from 2015-06-03 23-59-49](https://cloud.githubusercontent.com/assets/103854/7972447/cb4d7a3e-0a4c-11e5-8f8f-4d92e7af4e34.png)
![screenshot from 2015-06-04 00-00-04](https://cloud.githubusercontent.com/assets/103854/7972450/d1bd390e-0a4c-11e5-9c9b-9e1d0ba6c358.png)

As you can see, the overlays in the `;;` preceding the lisp comment at the top of the buffer are correct, i.e., every matching char is shown in blue.  This should also happen to the long semicolon sequences below but there blue and red alternate.

In contrast to @PythonNut, this is completely reproducible and deterministic here.  Or wait, it depends on length of, well, I don't really know.  All I can say is that THIS is displayed correctly
```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;
```
while THIS isn't
```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;
```

The difference is just that the latter has one semicolon more in the last line...

**Comment by abo-abo** [comment] 2015-06-04 07:34
> See the two screenshots which also contain the recipe.

I'd prefer not to copy sensitive text from the screenshot. Could you just paste the whole text here?

**Comment by tsdh** [comment] 2015-06-04 08:13
Yes, of course.  Consider this test file `avy-bug.el`.

```elisp
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;
```

Then start emacs like so: `emacs -Q -l ~/path/to/avy/avy.el --eval "(setq avy-style 'de-bruijn)" ~/avy-bug.el` and do `M-x avy-goto-char RET ;` and you'll get the wrong highlighting.

As soon as you delete one single `;` (no matter in which line) and try to jump to `;` again, the highlighting is correct.

Oh, it's actually the same when you put the contents all on the same line, or break it into 10 or 20 lines, or add spaces in between, etc..  So with the avy defaults, at most 81 consecutive (with only arbitrary whitespace in between) matches work, with 82 and up it doesn't anymore.

Hm, what's 81 for a magic number?  Well, by default `avy-keys` has the length 9, and `9^2` is 81...

**Comment by abo-abo** [comment] 2015-06-10 17:01
Can you check again? I think this could be fixed.

**Comment by tsdh** [comment] 2015-06-10 18:01
No, I'm sorry, it's still wrong in the same way as explained in my last comment: 81 consecutive matching chars => everything's ok, 82 consecutive matching chars => wrong highlighting.

**Comment by abo-abo** [comment] 2015-06-15 14:28
The bug was caused by the assumption that `overlays-in` is sorted (which it was randomly). Please check if it's fixed now.

**Closed** 2015-06-15 14:27 UTC

**Comment by tsdh** [comment] 2015-06-15 14:38
Yes, it is fixed.  Thanks a lot!
